### ISSUE TITLE
Add a event doesnt work

### ISSUE THREAD

**Issue by alain01** [tad0616/tad_cal#14]
Add a event doesnt work

May be cause this : 

- system_CleanVars() is deprecated since XOOPS 2.5.11, please use 'Xmf\Request' instead trace:
 \modules\system\include\functions.php:29 \modules\tad_cal\index.php:123
- system_CleanVars() is deprecated since XOOPS 2.5.11, please use 'Xmf\Request' instead trace: 
\modules\system\include\functions.php:29 \modules\tad_cal\index.php:124
- system_CleanVars() is deprecated since XOOPS 2.5.11, please use 'Xmf\Request' instead trace: 
\modules\system\include\functions.php:29 \modules\tad_cal\index.php:125- 

Version de XOOPS | XOOPS 2.5.11-Beta1
Version de PHP | 7.3.16
Version de mySQL | 8.0.16

**Comment by tad0616** [comment]
Got it! Thank you very much!
